### ISSUE TITLE
Add the aysnchronous notebook to the help pages

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/oda_api#1]
oda_api/doc/source/user_guide/AsynchronousAPI.ipynb

should appear on the help pages at https://oda-api.readthedocs.io/en/latest/

**Comment by volodymyrss** [comment]
please update the notebook mentioned in the issue oda_api/doc/source/user_guide/AsynchronousAPI.ipynb
and it should appear on the help pages at https://oda-api.readthedocs.io/en/latest/

**Comment by ferrigno** [comment]
See in the branch test_poll : it does not work with an exception that I do not understand.
