### ISSUE TITLE
unknown server-side error

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/oda_api#101]
Now, 13 runs finish, but then, I get this error.
UnexpectedDispatcherStatusCode: UnexpectedDispatcherStatusCode (line 78): status: 410, raw: {"cdci_data_analysis_version":"1.3.1","config":{"dispatcher-config":{"cfg_dict":{"dispatcher":{"bind_options":{"bind_host":"0.0.0.0","bind_port":8000},"dispatcher_callback_url_base":"http://dispatcher.production.iu.odahub.io:31611","dummy_cache":"dummy-cache","email_options":{"bcc_receivers_email_addresses":["vladimir.savchenko@gmail.com"],"cc_receivers_email_addresses":[],"email_sending_job_submitted":true,"email_sending_job_submitted_default_interval":1209600,"email_sending_timeout":true,"email_sending_timeout_default_threshold":1,"sender_email_address":"postmaster@in.odahub.io","smtp_port":25,"smtp_server":"postfix-relay"},"products_url":"https://frontend-staging.obsuks1.unige.ch/mmoda/"}},"origin":{"filepath":"/dispatcher/conf/conf_env.yml","set_by":"command line /pyenv/versions/3.8.5/lib/python3.8/site-packages/cdci_data_analysis/flask_app/app.py:cdci_data_analysis.flask_app.app"}},"plugins":{"cdci_magic_plugin":{"config_file":"/dispatcher/conf/conf.d/magic_data_server_conf.yml"},"cdci_osa_plugin":{"config_file":"/dispatcher/conf/conf.d/osa_data_server_conf.yml"},"cdci_polar_plugin":{"config_file":"/dispatcher/conf/conf.d/polar_data_server_conf.yml"},"dispatcher_plugin_antares":{"config_file":"/dispatcher/conf/conf.d/antares_data_server_conf.yml"},"dispatcher_plugin_integral_all_sky":{"config_file":"/pyenv/versions/3.8.5/lib/python3.8/site-packages/dispatcher_plugin_integral_all_sky/config_dir/data_server_conf.yml"}}},"debug_mode":"no","error_message":"Expecting value: line 1 column 1 (char 0)","installed_instruments":["magic","isgri","jemx","polar","antares","spi_acs"],"message":"request not valid","oda_api_version":"1.1.25"}

**Comment by volodymyrss** [comment]
the error is actually in the `error_message` field, this: `Expecting value: line 1 column 1 (char 0)`. Though it is not too informative in this case. I do not really see the error anymore. I suggest you repeat, and please let us know. 
The platform is loaded now, but it should work, maybe with retries.
If it happens now I will be more way to notice.

This error should not be generally retried, it typically has something to do with the input provided (which can not be decoded).

Also please upgrade oda_api to 1.1.26

**Comment by ferrigno** [comment]
Is it the master branch? I use it directly from my local clone of the git repository

**Comment by volodymyrss** [comment]
> Is it the master branch? I use it directly from my local clone of the git repository

In the pip. Generally, master is the latest "ready" but not sufficiently tried in the wild and hence not yet released  version. So latest master may be good to see sometimes. But I meant package version, in pip.

**Comment by volodymyrss** [comment]
> I managed to get some mosaics. Up to four requests, it works as expected. From the fifth (but it might by by chance), it submits, but it looks not yet done. However, I do not receive any email for submission, just received on email that it is done, without submission. 

It's the situation why we introduced a delay for second `submitted` email. You should have got it already before. But the job information must have expired since. There were many jobs, I cleaned a bit more intensively than usual,  usually I'd keep the mosaics, to prevent this.

> At the second attempt, it seem to find the product. I let it run and see if it gives an error.

It should just make the mosaic eventually.

It's also running my requests.

**Comment by volodymyrss** [comment]
I want to add into the release notes that we made some improvements to improve upon large requests: https://github.com/oda-hub/release-notes/blob/main/README.md
Since I managed to get these mosaics in different combinations, including much of the data from 2002-2022.
But I do not really want to send it unless you confirm that this works for you.

**Comment by volodymyrss** [comment]
Is it possible that your request now use distribution of scws per mosaic? It seems like it re-does the mosaics, from existing images.
To avoid this, it would be better to group in some persistent manner. E.g. by revolution, or by year than then subdivide.

**Comment by ferrigno** [comment]
It was actually done on purpose. One of the mosaics was extremely noisy and thus I subdivided the 300 scw list to isolate  the noisy part that was withing the first 100 scw. 

For the moment, I split the request in several steps and I am implementing a way to save mosaics locally, load them and sum them, but I have problems with your library for mosaics, debugging.

As soon as I managed, I will try to launch the entire bunch. Have you already processed the 2012-2021 data set?

**Comment by volodymyrss** [comment]
> It was actually done on purpose. One of the mosaics was extremely noisy and thus I subdivided the 300 scw list to isolate the noisy part that was withing the first 100 scw.

Could we then maybe conclude this issue here, so we do not confuse different activities? I was assuming your are still unable to get the mosaics due to some exception.
So is it still the problem?

> 
> For the moment, I split the request in several steps and I am implementing a way to save mosaics locally, load them and sum them, but I have problems with your library for mosaics, debugging.

Sorry to hear that!

> 
> As soon as I managed, I will try to launch the entire bunch. Have you already processed the 2012-2021 data set?

Not entirely, parts of it, for test.

Does the error fetching the mosaics persist, do the retries not happen?

**Comment by volodymyrss** [comment]
For another large bunch, in principle you can, but it might be useful to wait until what's running is done. Else you may  need to wait for currently running things for some time. As you wish.

**Comment by ferrigno** [comment]
We can close this issue. The error is not anymore present.
