### ISSUE TITLE
low server availability ?

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/oda_api#124]
I am resubmitting jobs, just using different lists of science windows, but spectra should be already in place, so just the summation is due.

I notice strange messages: 

- waiting for remote response (since 2022-02-12 18:17:36), please wait for https://www.astro.unige.ch/mmoda/dispatch-data/run_analysis
possibly temporary problem in calling server: ReadTimeout(ReadTimeoutError("HTTPSConnectionPool(host='www.astro.unige.ch', port=443): Read timed out. (read timeout=120)")) in 120.2 seconds, 199 tries left, sleeping 10 seconds until retry
- waiting for remote response (since 2022-02-12 18:19:46), please wait for https://www.astro.unige.ch/mmoda/dispatch-data/run_analysis

**Comment by volodymyrss** [comment]
I scale up the dispatcher now.

**Comment by volodymyrss** [comment]
and if it continues - please reopen
