### ISSUE TITLE
Using most recent astropy?

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/oda_api#125]
I am not sure if this is the right repository.
I run into strange errors with the format of the ISGRI response matrix when I manipulate it and I had to make odd patches
https://gitlab.astro.unige.ch/oda/api-clients/oda_api_wrapper/-/commit/fd8e2ed1ee5c5f3e0ee8489dae915fd773d58b94

I suspect that it might be due to compatibility issues with different versions of astropy.
It might be that it is the plugin that needs an update of the astropy version, or the dispatcher? 
@volodymyrss you can move this issues in case.

**Comment by volodymyrss** [comment]
I am not sure if this is still relevant. @ferrigno please re-open if needed.
