### ISSUE TITLE
Add tutorial for Legacy Survey

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/oda_api#129]

**Comment by dsavchenko** [comment]
While preparing the tutorial, I found that to use OdaImage one need to have an image product to be called exactly `mosaic_image_0_mosaic`  _(or to pass all the parameters to .show() method, which is not convenient at all)_
But where is this __mosaic_ suffix coming from? I can't grasp
@volodymyrss

**Comment by volodymyrss** [comment]
I would need to investigate. This part is from old code, not written by me, and in the time when we did not review code or even really discuss it. 
I made but did not complete another approach, convenient at least for my use. Using like that https://github.com/oda-hub/oda_api/blob/request-list/tests/test_basic.py#L406

**Comment by volodymyrss** [comment]
I suppose the name is constructed [here](https://github.com/oda-hub/oda_api/blob/0df6d12d30e3fbc01f7dc97a522d9bceb9230afe/oda_api/api.py#L1115-L1123). To change the name, you could probably adapt metadata?

**Comment by dsavchenko** [comment]
This one is targeted by #130
