### ISSUE TITLE
make sure to show warnings and comments are returned by the dispatcher

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/oda_api#152]

**Comment by volodymyrss** [comment]
do we actually show various dispatcher warnings in oda_api now ? @dsavchenko you dealt with this, right?

**Comment by dsavchenko** [comment]
In the oda_api I haven't implemented this yet

**Comment by dsavchenko** [comment]
Seems to be easy https://github.com/oda-hub/oda_api/pull/174
