### ISSUE TITLE
make guide for token operations

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/oda_api#16]

**Comment by ferrigno** [comment]
I need some basic instructions on how to use the api with a token ...

**Comment by volodymyrss** [comment]
As we discussed on Monday, you can use the "API code" button.
There should be another button leading there, not only after product.
But it should not be blocking.

**Comment by ferrigno** [comment]
Which is the parameter to be passed to API ?

**Comment by volodymyrss** [comment]
Please copy the API code, it has the code which passes the right parameters.

**Comment by ferrigno** [comment]
This is blocking me
https://github.com/oda-hub/doc-review-guidelines/issues/19

**Comment by volodymyrss** [comment]
for https://github.com/oda-hub/doc-review-guidelines/issues/19 , please use other instrument, which works, for now.
for https://github.com/oda-hub/doc-review-guidelines/issues/18 should be no problem for you, see there.
The problem is however this one https://github.com/oda-hub/dispatcher-app/issues/118

**Comment by ferrigno** [comment]
https://github.com/oda-hub/oda_api/blob/test_poll/doc/source/user_guide/Authentication.ipynb

It should be merged.

**Comment by burnout87** [comment]
If the relative PR is ready, it can be opened (now it is still a draft), ideally having someone reviewing it, and then merged

**Comment by volodymyrss** [comment]
the docs are available https://oda-api.readthedocs.io/en/latest/user_guide/Authentication.html
