### ISSUE TITLE
issue placing sources on image with ODA

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/oda_api#173]
Seems like maybe cat sources are not placed where they are in the image with oda_api.plot_tools? It looks
If it is indeed a problem, it can affect gallery.

![image](https://user-images.githubusercontent.com/3909535/206209117-1bf6f53e-6244-493f-b01a-bd5d38ed5022.png)
![image](https://user-images.githubusercontent.com/3909535/206209365-289fa84a-3fa3-417b-a3f2-12324b8acd9a.png)

You can look in this file, maybe start it in renkulab, or maybe go from the [query itself](https://www.astro.unige.ch/mmoda/?DEC=-0.013294166666666668&E1_keV=28.0&E2_keV=80.0&RA=40.66962125&T1=2001-03-06T13%3A26%3A48.000&T2=2023-03-06T15%3A32%3A27.000&T_format=isot&detection_threshold=7.0&instrument=isgri&integral_data_rights=public&max_pointings=500&osa_version=OSA11.2&product_type=isgri_image&query_status=new&query_type=Real&radius=15.0&src_name=NGC+1068&use_scws=no).

https://renkulab.io/gitlab/astronomy/mmoda/mmoda-request/-/blob/4c4a572c4d3202e3df3c97b004c89e87dab88b79/api_code_269c482f9da99daf.ipynb

We just deployed this feature token passing to renku (which allows to look on large results in renku), and @andriineronov  had a case related to the workshop here, I submitted it from phone, and explored in renku - all works!

**Comment by ferrigno** [comment]
This should solve the issue https://github.com/oda-hub/oda_api/pull/139/files/93fabfa89215b98f88c2157562b3685118d90157..0297568b95556133a08cc8b7f508fee226572e82

Not sure how to merge, as I am using this branch that Gabriele is developing.

**Comment by ferrigno** [comment]
I created a PR only with this modification https://github.com/oda-hub/oda_api/pull/175
It looks like something fails, I let @dsavchenko  or @burnout87  checking
