### ISSUE TITLE
Link not working on readthedocs

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/oda_api#186]
https://oda-api.readthedocs.io/en/latest/install.html

The link to the code at this page
https://github.com/oda-hub/oda_api/archive/refs/tags/v1.1.33.tar.gz
 is not working.

Can you correct it?

**Comment by burnout87** [comment]
Cannot find the correct one. I see tags until `1.1.31`. Where is the `1.1.33` located @volodymyrss  ?

**Comment by volodymyrss** [comment]
I updated it. It needs this https://github.com/oda-hub/oda_api/issues/156
Also the installation manual should be updated to refer to the code at github with git https://github.com/oda-hub/oda_api/issues/187 .
