### ISSUE TITLE
we should insert reasonable API code in the dispacher request

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/oda_api#19]
small adaptations are needed

**Comment by volodymyrss** [comment]
add a valid token

**Comment by burnout87** [comment]
Token is part of the API code.

What else is needed?

**Comment by volodymyrss** [comment]
Is it reasonable? Can we not an example here? masking token.

**Comment by burnout87** [comment]
this is an example (with masked token):
`from oda_api.api import DispatcherAPI

        disp=DispatcherAPI(host='https://frontend.staging.odahub.io/cdci/astrooda/dispatch-data',instrument='mock',cookies=cookies,protocol='https')
par_dict={'src_name': '4U 1700-377', 'RA': '257.815417', 'DEC': '-41.593417', 'T1': '2003-03-15T23:27:40.0', 'T2': '2003-03-16T00:03:15.0', 'T_format': 'isot', 'instrument': 'isgri', 'osa_version': 'OSA10.2', 'radius': '15', 'max_pointings': '50', 'integral_data_rights': 'public', 'E1_keV': '20', 'E2_keV': '40', 'product_type': 'Real', 'detection_threshold': '5', 'product': 'isgri_image', 'token': 'aaaaaaa.bbbbbbb.ccccccccc', 'user_catalog_file': None}
disp.get_product(**par_dict)`

What do you mean with reasonable?

**Comment by volodymyrss** [comment]
see there https://github.com/oda-hub/doc-review-guidelines/issues/20
cookies are not needed in released instance.

**Comment by ferrigno** [comment]
Also, host= should be changed in url=

**Comment by burnout87** [comment]
I need write permission to push changes to this repo. Could you please apply those to my account? Thanks

**Comment by volodymyrss** [comment]
You have the permissions since you asked:

![image](https://user-images.githubusercontent.com/3909535/119644126-d3667100-be1c-11eb-9697-178baf6781c2.png)

Was there no email?..
Sorry I did not reply into chat, I saw it in emails myself.
Please let  me know if there is any further issue!

**Comment by burnout87** [comment]
The email hasn't arrived (yet) but I see that I can now push changes, thanks
