### ISSUE TITLE
get_instruments_list, get_instrument_description don't use token

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/oda_api#196]

**Comment by burnout87** [comment]
No I haven't worked on it. How urgent it is ? As I have seen that the change has to be applied only on the `oda_api` side, so it won't a lot of development.

**Comment by burnout87** [comment]
#199 

should the same change applied also for `get_product_description`(and perhaps there are even more where this change is needed)

**Comment by burnout87** [comment]
> 
> should the same change applied also for `get_product_description`(and perhaps there are even more where this change is needed) ?

@dsavchenko Is then same change to be applied also for the `get_product_description` function?

**Comment by dsavchenko** [comment]
> @dsavchenko Is then same change to be applied also for the `get_product_description` function?

Yes, it should be, I think.

PS. sorry for delayed reply
