### ISSUE TITLE
Issue image processing

### ISSUE THREAD

**Issue by burnout87** [oda-hub/oda_api#202]
`the platfrom encourntered a bug which happens when ScW list is sent as a file; we are working on it! raw message: TypeError("\'name\' attribute must be a string)`

Is it a consequence of the changes introduced with #200 @dsavchenko ?

**Comment by dsavchenko** [comment]
Probably. Is it the error on dispatcher side?
Could you make a test to illustrate. Or show the request to reproduce?

**Comment by burnout87** [comment]
> Probably. Is it the error on dispatcher side? Could you make a test to illustrate. Or show the request to reproduce?

Yes, it is on the dispatcher side. I will make a test to reproduce it

**Comment by dsavchenko** [comment]
I think it's safe to restore name default value to string here https://github.com/oda-hub/oda_api/blob/8634e66bf429e138ef0d0ee0fa48629ea9b4f98b/oda_api/data_products.py#L225
as NumpyDataUnit not used as the top-level DataProduct, but only as its part.

**Comment by burnout87** [comment]
I will open a PR for that , I had already started one
