### ISSUE TITLE
add progress_max in progress report

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/oda_api#239]
could we?

**Comment by okolo** [comment]
@volodymyrss  how do you suggest to use this parameter?
Currently we have the following doc string for the parameters:
"""
        Report progress via callback URL
        :param stage: current stage description string
        :param progress: current stage progress in %
        :param substage: current substage description string
        :param subprogress: current substage progress in %
        :param message: message to pass
 """
i.e. we assume that progress is given in %. Do you suggest to give progress in arbitrary units and add progress_max parameter for relative progress calculation? In this case I would change description of the progress parameter to
:param progress: current stage progress
and add extra parameter:
:param progress_max: maximal progress value
Is it what you suggest?

**Comment by volodymyrss** [comment]
(sorry I edit your comment for readability)

Yes, I suggest to make the two parameters. Keeping the default of `progress_max` to `100`. 
Seems like people find it natural to have it so.
