### ISSUE TITLE
How to pass a long list of science windows to the API ?

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/oda_api#24]
I have a long list of science windows for a test case. 
Is it possible to pass it or should I should I use my "wrapper"?

**Comment by volodymyrss** [comment]
normally, just passing the same as before should work. It will change the request type, and give a warning message.

I just improved the test to make it more comprehensive, and made more log.

https://github.com/oda-hub/oda_api/blob/master/tests/test_live.py#L207

Please update oda_api to 1.1.10

**Comment by ferrigno** [comment]
Updated.
It seems you have (rightly) implemented some limitations. I will need to implement the token usage in calibration workflows

ESC[90m 2021-05-20T13:29:28 ESC[0m in <function DispatcherAPI.poll at 0x7f925cf4b0d0> called with:
ESC[90m 2021-05-20T13:29:28 ESC[0m ... [ DispatcherAPI: http://dispatcher.staging.internal.odahub.io ]
ESC[90m 2021-05-20T13:29:28 ESC[0m ... 
ESC[90m 2021-05-20T13:29:28 ESC[0m possible causes:
ESC[90m 2021-05-20T13:29:28 ESC[0m - connection error
ESC[90m 2021-05-20T13:29:28 ESC[0m - wrong credentials
ESC[90m 2021-05-20T13:29:28 ESC[0m - error on the remote server
ESC[90m 2021-05-20T13:29:28 ESC[0m  exception message: 
ESC[90m 2021-05-20T13:29:28 ESC[0m 
ESC[90m 2021-05-20T13:29:28 ESC[0m UnexpectedDispatcherStatusCode (line 66): status: 403, raw: {"exit_status":{"comment":"","debug_message":"","error_message":"","job_status":"failed","message":"Roles [] not authorized to request the product isgri_spectrum, ['unige-hpc-full'] roles are needed","status":1,"warning":""},"job_monitor":{"job_id":"0e06fa840996e4f1","session_id":"CFFND9R51QL02GN4","status":"failed"},"job_status":"failed","products":{},"query_status":"failed","session_id":"CFFND9R51QL02GN4","status_code":403,"time_request":1621510168.135405}
ESC[90m 2021-05-20T13:29:28 ESC[0m 
ESC[90m 2021-05-20T13:29:28 ESC[0m Traceback (most recent call last):
ESC[90m 2021-05-20T13:29:28 ESC[0m   File "/pyenv/versions/3.8.2/lib/python3.8/site-packages/oda_api/api.py", line 97, in func_wrapper
ESC[90m 2021-05-20T13:29:28 ESC[0m     return func(*args, **kwargs)
ESC[90m 2021-05-20T13:29:28 ESC[0m   File "/pyenv/versions/3.8.2/lib/python3.8/site-packages/oda_api/api.py", line 484, in poll
ESC[90m 2021-05-20T13:29:28 ESC[0m     self.response_json = self.request_to_json()
ESC[90m 2021-05-20T13:29:28 ESC[0m   File "/pyenv/versions/3.8.2/lib/python3.8/site-packages/oda_api/api.py", line 322, in request_to_json
ESC[90m 2021-05-20T13:29:28 ESC[0m     raise UnexpectedDispatcherStatusCode(
ESC[90m 2021-05-20T13:29:28 ESC[0m oda_api.api.UnexpectedDispatcherStatusCode: UnexpectedDispatcherStatusCode (line 66): status: 403, raw: {"exit_status":{"comment":"","debug_message":"","error_message":"","job_status":"failed","message":"Roles [] not authorized to request the product isgri_spectrum, ['unige-hpc-full'] roles are needed","status":1,"warning":""},"job_monitor":{"job_id":"0e06fa840996e4f1","session_id":"CFFND9R51QL02GN4","status":"failed"},"job_status":"failed","products":{},"query_status":"failed","session_id":"CFFND9R51QL02GN4","status_code":403,"time_request":1621510168.135405}

**Comment by ferrigno** [comment]
Strange enough. With 5 scw, the call is accepted, but it makes a slightly confusing warning.

C[90m 2021-05-20T13:33:07 ESC[0m 2021-05-20 11:33:07,566 - papermill - WARNING - 2021-05-20 11:33:07,563 - papermill - WARNING - switching to POST request due to large payload: 1501 > 1000

**Comment by volodymyrss** [comment]
This warning might not be relevant indeed.
So, you are going to use the wrapper to circumvent the restriction? :)
