### ISSUE TITLE
SPI ACS light curve not returned: non informative error shown to user

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/oda_api#25]
<div class="modal-header"><h4 class="modal-title">Processing ...</h4>
        <div class="header-message" style="display: block;">
          <div>
            Session : <span class="session-id">R5AX8HSAQM66FYBB</span> | Job Id : <span class="job-id">3dd9a8ea3ba25dbb</span>
          </div>
        </div>
      </div>
      <div class="modal-body">
        
        <div class="summary"><div class="alert alert-danger">
2021.05.20T09:02:37 | failed: spi_acs_lc
-- | --
&nbsp; | SpiacsAnalysisException("spiacs light curve failed: ValueError('no field of name ERROR')")

</div></div></div>

**Comment by volodymyrss** [comment]
Could you please clarify, when this happens? Frontend or API? (this is API repository here).  What request?

**Comment by ferrigno** [comment]
I do not remember closing and open a new one.
