### ISSUE TITLE
astropy no units member in test?

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/oda_api#251]
that's weird, interesting for everybody. If someone has an idea or can have a look, please comment!

**Comment by dsavchenko** [comment]
I think here it is https://stackoverflow.com/questions/49846940/incorrect-pylint-errors-on-astropy-in-vscode
And we saw it already somewhere, as far as I remember. I'll try to fix.

Why has it appeared only now? Were there some changes in the linter settings?
