### ISSUE TITLE
get instrument description returns badly formatted code

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/oda_api#28]
disp.get_instrument_description('isgri')

Used to be much better formatted. Now, it is not confortably readable.

[[{'instrumet': 'isgri'},
  {'prod_dict': {'isgri_image': 'isgri_image_query',
    'isgri_lc': 'isgri_lc_query',
    'isgri_spectrum': 'isgri_spectrum_query',
    'spectral_fit': 'spectral_fit_query'}},
  '[{"query_name": "src_query"}, {"name": "src_name", "units": "str", "value": "test"}, {"name": "RA", "units": "deg", "value": 0.0}, {"name": "DEC", "units": "deg", "value": 0.0}, {"name": "T1", "units": None, "value": "2001-12-11T00:00:00.000"}, {"name": "T2", "units": None, "value": "2001-12-11T00:00:00.000"}, {"name": "token", "units": "str", "value": None}]',
  '[{"query_name": "isgri_parameters"}, {"name": "user_catalog", "units": "str", "value": None}, {"name": "scw_list", "units": "names_list", "value": []}, {"name": "selected_catalog", "units": "str", "value": None}, {"name": "radius", "units": "deg", "value": 5.0}, {"name": "max_pointings", "units": None, "value": 50}, {"name": "osa_version", "units": "str", "value": None}, {"name": "integral_data_rights", "units": "str", "value": "public"}, {"name": "E1_keV", "units": "keV", "value": 10.0}, {"name": "E2_keV", "units": "keV", "value": 40.0}]',
  '[{"query_name": "isgri_image_query"}, {"product_name": "isgri_image"}, {"name": "detection_threshold", "units": "sigma", "value": 0.0}, {"name": "image_scale_min", "units": None, "value": None}, {"name": "image_scale_max", "units": None, "value": None}]',
  '[{"query_name": "isgri_spectrum_query"}, {"product_name": "isgri_spectrum"}]',
  '[{"query_name": "isgri_lc_query"}, {"product_name": "isgri_lc"}, {"name": "time_bin", "units": "sec", "value": 1000.0}]',
  '[{"query_name": "spectral_fit_query"}, {"product_name": "spectral_fit"}, {"name": "xspec_model", "units": "str", "value": "powerlaw"}, {"name": "ph_file_name", "units": "str", "value": ""}, {"name": "arf_file_name", "units": "str", "value": ""}, {"name": "rmf_file_name", "units": "str", "value": ""}]']]

**Comment by volodymyrss** [comment]
get_instrument_description returns a python structure, not formatted.
It used to return nothing.
It also prints in logging. It used to print in print.
Could it be you did not enable logging and what surprises you is the returned value?

**Comment by volodymyrss** [comment]
As far as I am concerned, it is printing  just as before, and also returning python object, which may be formatted by jupyter and confuse people. But that's not something that should be changed.

Please reopen if I misunderstood.
