### ISSUE TITLE
Conda package build fails starting from 1.2.30

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/oda_api#303]
@dsavchenko  @volodymyrss  it seems to me that starting 1.2.30 the build test is failing : https://dev.azure.com/conda-forge/feedstock-builds/_build?definitionId=20327&_a=summary and the latest version on conda-forge 1.2.28. So I suppose that given the failed tests, the oda-api package is not updated. Could this be the case? Thanks!

_Originally posted by @Andrei-EPFL in https://github.com/esg-epfl-apc/tools-astro/issues/149#issuecomment-2490402349_

**Comment by dsavchenko** [comment]
oda_api build in conda is fixed
