### ISSUE TITLE
`Executing Notebook` unable to run

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/oda_api#308]
This [action](https://github.com/oda-hub/oda_api/actions/runs/12051921242/job/33604068425?pr=307) runs in a container `integralsw/osa-python:auto-latest`. This container isn't compatible with `node20` used by github actions. Before, it was possible to allow deprecated `node16` by setting `ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true` in workflow file, but seems that it has just stopped working. 

The only way I see is to update the container, which might be nontrivial...

**Comment by volodymyrss** [comment]
I think @ferrigno was updating the container recently, right?

**Comment by ferrigno** [comment]
Recently is about a year ago. Then,  I tried to move to another Linux distribution,  but did not manage to finish.  It might take weeks before I manage to put my hands on this again.

**Comment by volodymyrss** [comment]
Ok then, I suggest to drop INTEGRAL-specific tests from these notebooks, and make the base image a lot lighter.

**Comment by ferrigno** [comment]
What are the implications for MMODA? We have the duty to keep INTEGRAL online analysis up and running. We used many resources from ISDC funds for this platform and this part cannot be dropped.

**Comment by ferrigno** [comment]
What are the implications for MMODA? We have the duty to keep INTEGRAL online analysis up and running. We used many resources from ISDC funds for this platform and this part cannot be dropped.

**Comment by ferrigno** [comment]
@dsavchenko what is node16 and node20 ? A python tool or a linux one?

**Comment by dsavchenko** [comment]
> @dsavchenko what is node16 and node20 ? A python tool or a linux one?

node.js, a JavaScript runtime environnement used by github to execute actions.

**Comment by dsavchenko** [comment]
Do we really need an integral container for this? As far as I see from the `Asynchronous-API.ipynb` (the notebook that runs here), what's really needed for this action, is `pyXspec`. 

I don't even see any use of the integral fork of `astroquery` that's installed in the action...

Do I miss something? Or we can just use any container with `heasoft` installed. The [standard Dockerfile](https://heasarc.gsfc.nasa.gov/docs/software/heasoft/docker.html) they propose is based on ubuntu-22.04, this should be compatible with the github actions.

**Comment by volodymyrss** [comment]
> Do we really need an integral container for this? As far as I see from the `Asynchronous-API.ipynb` (the notebook that runs here), what's really needed for this action, is `pyXspec`.
> 
> I don't even see any use of the integral fork of `astroquery` that's installed in the action...
> 
> Do I miss something? Or we can just use any container with `heasoft` installed. The [standard Dockerfile](https://heasarc.gsfc.nasa.gov/docs/software/heasoft/docker.html) they propose is based on ubuntu-22.04, this should be compatible with the github actions.

It needs heasoft with a compatible version of python compiled-in. It used to be that they did not have it or had old one, maybe they should work now.

Could you please switch?

**Comment by dsavchenko** [comment]
I will try
