### ISSUE TITLE
jsonification is does not always produce valid python

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/oda_api#38]
requests currently return this:

```python
from oda_api.api import DispatcherAPI
disp=DispatcherAPI(url='http://0.0.0.0:8000', instrument='mock')

par_dict={
    "src_name": "4U 1700-377",
    "RA": "257.815417",
    "DEC": "-41.593417",
    "T1": "2003-03-15T23:27:40.0",
    "T2": "2003-03-16T00:03:15.0",
    "T_format": "isot",
    "instrument": "spi_acs",
    "product_type": "Real",
    "product": "spi_acs_lc",
    "time_bin": "2",
    "user_catalog_file": null
}

data_collection = disp.get_product(**par_dict)
```

`"user_catalog_file": null ` is not python. It should be skipped.

It's not easy to reproduce, since None will not be passed to the dispatcher, but this `user_catalog_file` is set in a special way in the plugin.

Also url is not ok, it comes from config?

**Comment by burnout87** [comment]
[https://github.com/oda-hub/dispatcher-app/blob/c0ee7a971ae79a605752eb3b9ae19e956c077ff0/cdci_data_analysis/analysis/instrument.py#L255](https://github.com/oda-hub/dispatcher-app/blob/c0ee7a971ae79a605752eb3b9ae19e956c077ff0/cdci_data_analysis/analysis/instrument.py#L255)

**Comment by burnout87** [comment]
Is the `null` value set in case of a `None` ?

**Comment by volodymyrss** [comment]
> https://github.com/oda-hub/dispatcher-app/blob/c0ee7a971ae79a605752eb3b9ae19e956c077ff0/cdci_data_analysis/analysis/instrument.py#L255

ok, I overlooked.  It should be derived from products_url.

But it also duplicates this:

https://github.com/oda-hub/frontend-astrooda/blob/master/js/astrooda.instrument.js#L164

And possibly the frontend-way is more reliable.
It only stopped working because of change from `host=` to `url=`. We should make that change in the frontend.

**Comment by burnout87** [comment]
> > https://github.com/oda-hub/dispatcher-app/blob/c0ee7a971ae79a605752eb3b9ae19e956c077ff0/cdci_data_analysis/analysis/instrument.py#L255
> 
> ok, I overlooked. It should be derived from products_url.
> 
> But it also duplicates this:
> 
> https://github.com/oda-hub/frontend-astrooda/blob/master/js/astrooda.instrument.js#L164
> 
> And possibly the frontend-way is more reliable.
> It only stopped working because of change from `host=` to `url=`. We should make that change in the frontend.

I suppose that also in the frontend a little change will be necessary?
