### ISSUE TITLE
emailed python api code cannot be copied and pasted

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/oda_api#41]
I copied and pasted the code in the email with title 
[ODA][done] isgri_spectrum first requested at 2021-05-31 08:21:57 job_id: db2ef7ab

from oda_api.api import DispatcherAPI
disp=DispatcherAPI(url='www.astro.unige.ch/cdci/astrooda/dispatch-data', instrument='mock')

par_dict={
"src_name": "Swift J1749.4-2807",
"RA": "267.38308333",
"DEC": "-28.13494444",
"T1": "2021-02-20T00:00:00",
"T2": "2021-03-16T00:00:00",
"T_format": "isot",
"instrument": "isgri",
"osa_version": "OSA11.0",
"radius": "8",
"max_pointings": "20",
"integral_data_rights": "all-private",
"E1_keV": "28",
"E2_keV": "80",
"product_type": "Real",
"detection_threshold": "5",
"product": "isgri_spectrum",
"catalog_selected_objects": "1,2,3,4,5,6,7,8",
"selected_catalog": "{\"cat_column_descr\":[[\"meta_ID\",\"f4\"],[\"ra\",\">f4\"],[\"dec\",\">f4\"],[\"NEW_SOURCE\",\">i2\"],[\"ISGRI_FLAG\",\" "token": "",
"user_catalog_file": null
}

data_collection = disp.get_product(**par_dict) 

but got

  File "<ipython-input-1-2aabc40aaa86>", line 22
    "selected_catalog": "{\"cat_column_descr\":[[\"meta_ID\",\"f4\"],[\"ra\",\">f4\"],[\"dec\",\">f4\"],[\"NEW_SOURCE\",\">i2\"],[\"ISGRI_FLAG\",\" "token": "",
                                                                                                                                                     ^
SyntaxError: invalid syntax

**Comment by burnout87** [comment]
> Oh but it's oda_api version/problem, not dispatcher-app. Updating.

Exaclty. The check happens within the `oda_api`

**Comment by volodymyrss** [comment]
> > Oh but it's oda_api version/problem, not dispatcher-app. Updating.
> 
> Exaclty. The check happens within the `oda_api`

thank you for confirming!

**Comment by volodymyrss** [comment]
I close since new oda_api seems to resolve it. If not solved please reopen.
