### ISSUE TITLE
API code from Frontend not woking

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/oda_api#42]
The web interface returned a correct result, but the API code does not work

![image](https://user-images.githubusercontent.com/2527219/120620187-003e0800-c45d-11eb-8cff-91e06d427610.png)

/home/ferrigno/Soft/myVE-py37/bin/python
Python 3.7.5
oda-api==1.1.12

from oda_api.api import DispatcherAPI
disp=DispatcherAPI(url='https://frontend.staging.odahub.io/cdci/astrooda/', instrument='mock')

par_dict={
    "src_name": "4U 1700-377",
    "RA": "255.986542",
    "DEC": "-37.844167",
    "T1": "53417.22",
    "T2": "53417.32",
    "T_format": "mjd",
    "instrument": "spi_acs",
    "product_type": "Real",
    "product": "spi_acs_lc",
    "time_bin": "1",
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IkNhcmxvLkZlcnJpZ25vQHVuaWdlLmNoIiwibmFtZSI6ImNmZXJyaWdubyIsInJvbGVzIjoiYXV0aGVudGljYXRlZCB1c2VyLCBhZG1pbmlzdHJhdG9yLCBjb250ZW50IG1hbmFnZXIsIGdlbmVyYWwsIGludGVncmFsLXByaXZhdGUtcWxhLCBtYWdpYywgdW5pZ2UtaHBjLWZ1bGwsIHB1YmxpYy1wb29sLWhwYywgYW50YXJlcywgc2RzcyIsImV4cCI6MTYyMjc5NTgwNn0.wOXZ9GlhPMZ8eR-LKYFIbAgl3V_ZzTqWBAInkWknzN8"
}

data_collection = disp.get_product(**par_dict)

**Comment by ferrigno** [comment]
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-3-fe6a3211a9b1> in <module>
     16 }
     17 
---> 18 data_collection = disp.get_product(**par_dict)

~/Soft/myVE-py37/lib/python3.7/site-packages/oda_api/api.py in get_product(self, product, instrument, verbose, dry_run, product_type, **kwargs)
    831 
    832         # >
--> 833         self.request(kwargs)
    834 
    835         if self.is_failed:

~/Soft/myVE-py37/lib/python3.7/site-packages/oda_api/api.py in func_wrapper(*args, **kwargs)
    107         while True:
    108             try:
--> 109                 return func(*args, **kwargs)
    110             except UserError as e:
    111                 logger.exception("user error: %s", e)

~/Soft/myVE-py37/lib/python3.7/site-packages/oda_api/api.py in request(self, parameters_dict, handle, url, wait, quiet)
    612 
    613         while True:
--> 614             self.poll()
    615 
    616             if not self.wait:

~/Soft/myVE-py37/lib/python3.7/site-packages/oda_api/api.py in func_wrapper(*args, **kwargs)
    107         while True:
    108             try:
--> 109                 return func(*args, **kwargs)
    110             except UserError as e:
    111                 logger.exception("user error: %s", e)

~/Soft/myVE-py37/lib/python3.7/site-packages/oda_api/api.py in poll(self, verbose, silent)
    509 
    510         # >
--> 511         self.response_json = self.request_to_json()
    512         # <
    513 

~/Soft/myVE-py37/lib/python3.7/site-packages/oda_api/api.py in request_to_json(self, verbose)
    340 
    341             if response.status_code == 403:
--> 342                 raise Unauthorized(response.json()['exit_status']['message'])
    343 
    344             if response.status_code == 400:

~/Soft/myVE-py37/lib/python3.7/site-packages/requests/models.py in json(self, **kwargs)
    898                     # used.
    899                     pass
--> 900         return complexjson.loads(self.text, **kwargs)
    901 
    902     @property

~/Soft/myVE-py37/lib/python3.7/site-packages/simplejson/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, use_decimal, **kw)
    523             parse_constant is None and object_pairs_hook is None
    524             and not use_decimal and not kw):
--> 525         return _default_decoder.decode(s)
    526     if cls is None:
    527         cls = JSONDecoder

~/Soft/myVE-py37/lib/python3.7/site-packages/simplejson/decoder.py in decode(self, s, _w, _PY3)
    368         if _PY3 and isinstance(s, bytes):
    369             s = str(s, self.encoding)
--> 370         obj, end = self.raw_decode(s)
    371         end = _w(s, end).end()
    372         if end != len(s):

~/Soft/myVE-py37/lib/python3.7/site-packages/simplejson/decoder.py in raw_decode(self, s, idx, _w, _PY3)
    398             elif ord0 == 0xef and s[idx:idx + 3] == '\xef\xbb\xbf':
    399                 idx += 3
--> 400         return self.scan_once(s, idx=_w(s, idx).end())

JSONDecodeError: Expecting value: line 2 column 1 (char 1)

**Comment by burnout87** [comment]
Looks like expired token, is a `403` message.

**Comment by volodymyrss** [comment]
is this not the same as https://github.com/oda-hub/doc-review-guidelines/issues/30 ?

the problem is essentially that you can not request github-secured host without extra authentication. Please use internal version.

this will be easier to do correctly when we have public live URL instance. 

we could make more clear response, but in this case from point of view of oda_api it is getting random html page. 
So extra message would be some detection that it is not json and suggest that

**Comment by volodymyrss** [comment]
> Looks like expired token, is a `403` message.

that would return adequate error message, and will be shown properly by the api.

**Comment by ferrigno** [comment]
I login with github, then properly logged in on Drupal ... very weird

**Comment by volodymyrss** [comment]
> I login with github, then properly logged in on Drupal ... very weird

this is not applicable for the guide, but staging frontend is secured by an extra level, blocking even access to the frontend page. It's needed since it may have vulnerabilities, even before login.

API needs to get through this extra level (can be done but putting a cookie) to even talk to dispatcher, and then need to support query with a token.

If you are internal - you can just always use internal URL, all of this confusion should be avoided.

**Comment by ferrigno** [comment]
I continue not to understand. I removed the token from the api_request and got the same error.

What should I use ?

from oda_api.api import DispatcherAPI
disp=DispatcherAPI(url='http://frontend.staging.odahub.io/cdci/astrooda/', instrument='mock')

par_dict={
    "src_name": "4U 1700-377",
    "RA": "255.986542",
    "DEC": "-37.844167",
    "T1": "53417.22",
    "T2": "53417.32",
    "T_format": "mjd",
    "instrument": "spi_acs",
    "product_type": "Real",
    "product": "spi_acs_lc",
    "time_bin": "1"
}

data_collection = disp.get_product(**par_dict)

**Comment by ferrigno** [comment]
It works using this.
disp=DispatcherAPI(url='http://dispatcher.staging.internal.odahub.io/', instrument='mock')
