### ISSUE TITLE
name of product in .show() is not correct

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/oda_api#43]
<code>
from oda_api.api import DispatcherAPI
disp=DispatcherAPI(url='http://dispatcher.staging.internal.odahub.io/', instrument='mock')

par_dict={
    "src_name": "4U 1700-377",
    "RA": "270.80",
    "DEC": "-29.80",
    "T1": "2021-05-01",
    "T2": "2021-05-05",
    "T_format": "isot",
    "instrument": "jemx",
    "osa_version": "OSA11.0",
    "radius": "4",
    "max_pointings": "50",
    "integral_data_rights": "all-private",
    "jemx_num": "1",
    "E1_keV": "3",
    "E2_keV": "35",
    "product_type": "Real",
    "detection_threshold": "5",
    "product": "jemx_spectrum",
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IkNhcmxvLkZlcnJpZ25vQHVuaWdlLmNoIiwibmFtZSI6ImNmZXJyaWdubyIsInJvbGVzIjoiYXV0aGVudGljYXRlZCB1c2VyLCBhZG1pbmlzdHJhdG9yLCBjb250ZW50IG1hbmFnZXIsIGdlbmVyYWwsIGludGVncmFsLXByaXZhdGUtcWxhLCBtYWdpYywgdW5pZ2UtaHBjLWZ1bGwsIHB1YmxpYy1wb29sLWhwYywgYW50YXJlcywgc2RzcyIsImV4cCI6MTYyMjgwOTk2MH0.lDq2vVob0H25V0bYo9UriP6oBlOhVLPRgVJe4rRLlhU"
}

data_collection = disp.get_product(**par_dict)

data_collection.show()
</code>
ID=0 prod_name=jemx_spectrum_0_GX5-1_jemx_spectrum  meta_data: {'src_name': 'GX 5-1', 'product': 'jemx_spectrum'}
...
ID=3 prod_name=jemx_spectrum_3_H1820-303_jemx_spectrum  meta_data: {'src_name': 'H 1820-303', 'product': 'jemx_spectrum'}
...

provides names with a "-" minus, but the accessed name is with "m" 

data_collection.jemx_spectrum_0_GX5m1_jemx_spectrum

can we correct this behavior ?

[I remember to have it raised already, but I do not find this issue anymore]

**Comment by burnout87** [comment]
To check also for the "+" sign presence.

**Comment by volodymyrss** [comment]
is this it https://github.com/oda-hub/dispatcher-plugin-integral/issues/1

**Comment by volodymyrss** [comment]
close since it is a duplicate
