### ISSUE TITLE
unwanted warning on oda_api code

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/oda_api#59]
I got this api_code from the frontend (very nice feature!) but I get a slightly confusing warning

```python
from oda_api.api import DispatcherAPI
disp=DispatcherAPI(url='https://www.astro.unige.ch/mmoda//dispatch-data', instrument='mock')

par_dict={
    "src_name": "GRB170325B",
    "RA": "",
    "DEC": "",
    "T1": "2017-03-25T21:49:01.00",
    "T2": "2017-03-25T21:51:01.00",
    "T_format": "isot",
    "instrument": "spi_acs",
    "product_type": "Real",
    "product": "spi_acs_lc",
    "time_bin": "1"
}
data_collection = disp.get_product(**par_dict)
```

(with logging at INFO level gives )

```
unable to dig list, instance not a dict by <class 'NoneType'>; object was None
/home/ferrigno/Soft/myVE-py37/lib/python3.7/site-packages/oda_api/api.py:846: UserWarning: 
----------------------------------------------------------------------------
the parameter: T_format   is not among valid ones:
['src_name', 'RA', 'DEC', 'T1', 'T2', 'token', None, 'selected_catalog', 'time_bin']
this will throw an error in a future version 
and might breack the current request!
 ----------------------------------------------------------------------------
```

**Comment by volodymyrss** [comment]
It's sufficient to make a one-line change (warning => debug). But maybe it's useful if @burnout87 looks on that part to be familiar why this warning is even there. What do you think, @burnout87 ?

**Comment by burnout87** [comment]
Ok, I am actually doing some debugging, but it seems that it comes from the way the spi_acs instrument is initialized.

**Comment by burnout87** [comment]
Ok, I was wrong, it has nothing to do with the way the plugin of `spi_acs` is initialized.

It is rather because `T_format` is not actually treated as a parameter, but rather used in different context, which I haven't understood yet. 

But since it appears in the list of input parameters the warning is issued.

I will change to a debug level log message.

**Comment by volodymyrss** [comment]
Removed with #61 unless  not.

**Comment by burnout87** [comment]
Apparently the message still appears, as noted by @ferrigno

**Comment by volodymyrss** [comment]
and still appears?

**Comment by burnout87** [comment]
I remember that probably @ferrigno  was missing the most up -to-date version of `oda_api`. Did you double check @ferrigno ?

**Comment by ferrigno** [comment]
I have not seen unwanted warning lately.
