### ISSUE TITLE
in some cases, ScW list is not correctly passed in the parameter list

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/oda_api#66]
https://github.com/oda-hub/doc-review-guidelines/issues/57

**Comment by volodymyrss** [comment]
it's kind of important. 

I suppose it happens when parameter is python `list`. It's converted into a `str`, so it looks like `["xxx", "yyy", ...]`. Frontend does not appreciate this.

**Comment by burnout87** [comment]
Indeed frontend does not like when scw_list is a list of string

**Comment by volodymyrss** [comment]
> Indeed frontend does not like when scw_list is a list of string

So url in the email should be constructed specially in such a case.

**Comment by volodymyrss** [comment]
is this ok @burnout87 ? I guess so.

**Comment by burnout87** [comment]
Yes. But it would be good to have a confirmation with one practical test from @ferrigno

**Comment by burnout87** [comment]
Waas this re-tried?

**Comment by volodymyrss** [comment]
let's just close this and keep https://github.com/oda-hub/doc-review-guidelines/issues/57
