### ISSUE TITLE
disp=DispatcherAPI(url='www.astro.unige.ch/mmoda/dispatch-data',instrument='mock',protocol='https') leads to errors

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/oda_api#69]
This is the code snippet

```
from oda_api.api import DispatcherAPI
disp=DispatcherAPI(url='www.astro.unige.ch/mmoda/dispatch-data',instrument='mock',protocol='https')
instr_list=disp.get_instruments_list()
```

and the error

---------------------------------------------------------------------------
MissingSchema                             Traceback (most recent call last)
/tmp/ipykernel_27707/1955644526.py in <module>
----> 1 instr_list=disp.get_instruments_list()
      2 for i in instr_list:
      3     print (i)

~/.venv/myVE/lib/python3.8/site-packages/oda_api/api.py in func_wrapper(*args, **kwargs)
    118         while True:
    119             try:
--> 120                 return func(*args, **kwargs)
    121             except UserError as e:
    122                 logger.exception("user error: %s", e)

~/.venv/myVE/lib/python3.8/site-packages/oda_api/api.py in get_instruments_list(self)
    784     def get_instruments_list(self):
    785         #print ('instr',self.instrument)
--> 786         res = requests.get("%s/api/instr-list" % self.url,
    787                            params=dict(instrument=self.instrument), cookies=self.cookies)
    788 

~/.venv/myVE/lib/python3.8/site-packages/requests/api.py in get(url, params, **kwargs)
     73     """
     74 
---> 75     return request('get', url, params=params, **kwargs)
     76 
     77 

~/.venv/myVE/lib/python3.8/site-packages/requests/api.py in request(method, url, **kwargs)
     59     # cases, and look like a memory leak in others.
     60     with sessions.Session() as session:
---> 61         return session.request(method=method, url=url, **kwargs)
     62 
     63 

~/.venv/myVE/lib/python3.8/site-packages/requests/sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    526             hooks=hooks,
    527         )
--> 528         prep = self.prepare_request(req)
    529 
    530         proxies = proxies or {}

~/.venv/myVE/lib/python3.8/site-packages/requests/sessions.py in prepare_request(self, request)
    454 
    455         p = PreparedRequest()
--> 456         p.prepare(
    457             method=request.method.upper(),
    458             url=request.url,

~/.venv/myVE/lib/python3.8/site-packages/requests/models.py in prepare(self, method, url, headers, files, data, params, auth, cookies, hooks, json)
    314 
    315         self.prepare_method(method)
--> 316         self.prepare_url(url, params)
    317         self.prepare_headers(headers)
    318         self.prepare_cookies(cookies)

~/.venv/myVE/lib/python3.8/site-packages/requests/models.py in prepare_url(self, url, params)
    388             error = error.format(to_native_string(url, 'utf8'))
    389 
--> 390             raise MissingSchema(error)
    391 
    392         if not host:

MissingSchema: Invalid URL 'www.astro.unige.ch/mmoda/dispatch-data/api/instr-list': No schema supplied. Perhaps you meant http://www.astro.unige.ch/mmoda/dispatch-data/api/instr-list?

**Comment by volodymyrss** [comment]
> The issue is solved if I use
> 
> disp=DispatcherAPI(url='https://www.astro.unige.ch/mmoda/dispatch-data',instrument='mock')
> 
this is the correct form!

> to initialize the dispatcher, we should disable the other form
it is currently warned, and may be warned harder, but constructed for consistency.
and raise error if ambigious.

**Comment by volodymyrss** [comment]
> This is the code snippet
> 
> ```
> from oda_api.api import DispatcherAPI
> disp=DispatcherAPI(url='www.astro.unige.ch/mmoda/dispatch-data',instrument='mock',protocol='https')
> instr_list=disp.get_instruments_list()
> ```
> 
> and the error
> 
> MissingSchema Traceback (most recent call last)
> /tmp/ipykernel_27707/1955644526.py in
> ----> 1 instr_list=disp.get_instruments_list()
> 2 for i in instr_list:
> 3 print (i)
> 
> ~/.venv/myVE/lib/python3.8/site-packages/oda_api/api.py in func_wrapper(*args, **kwargs)
> 118 while True:
> 119 try:
> --> 120 return func(*args, **kwargs)
> 121 except UserError as e:
> 122 logger.exception("user error: %s", e)
> 
> ~/.venv/myVE/lib/python3.8/site-packages/oda_api/api.py in get_instruments_list(self)
> 784 def get_instruments_list(self):
> 785 #print ('instr',self.instrument)
> --> 786 res = requests.get("%s/api/instr-list" % self.url,
> 787 params=dict(instrument=self.instrument), cookies=self.cookies)
> 788
> 
> ~/.venv/myVE/lib/python3.8/site-packages/requests/api.py in get(url, params, **kwargs)
> 73 """
> 74
> ---> 75 return request('get', url, params=params, **kwargs)
> 76
> 77
> 
> ~/.venv/myVE/lib/python3.8/site-packages/requests/api.py in request(method, url, **kwargs)
> 59 # cases, and look like a memory leak in others.
> 60 with sessions.Session() as session:
> ---> 61 return session.request(method=method, url=url, **kwargs)
> 62
> 63
> 
> ~/.venv/myVE/lib/python3.8/site-packages/requests/sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
> 526 hooks=hooks,
> 527 )
> --> 528 prep = self.prepare_request(req)
> 529
> 530 proxies = proxies or {}
> 
> ~/.venv/myVE/lib/python3.8/site-packages/requests/sessions.py in prepare_request(self, request)
> 454
> 455 p = PreparedRequest()
> --> 456 p.prepare(
> 457 method=request.method.upper(),
> 458 url=request.url,
> 
> ~/.venv/myVE/lib/python3.8/site-packages/requests/models.py in prepare(self, method, url, headers, files, data, params, auth, cookies, hooks, json)
> 314
> 315 self.prepare_method(method)
> --> 316 self.prepare_url(url, params)
> 317 self.prepare_headers(headers)
> 318 self.prepare_cookies(cookies)
> 
> ~/.venv/myVE/lib/python3.8/site-packages/requests/models.py in prepare_url(self, url, params)
> 388 error = error.format(to_native_string(url, 'utf8'))
> 389
> --> 390 raise MissingSchema(error)
> 391
> 392 if not host:
> 
> MissingSchema: Invalid URL 'www.astro.unige.ch/mmoda/dispatch-data/api/instr-list': No schema supplied. Perhaps you meant http://www.astro.unige.ch/mmoda/dispatch-data/api/instr-list?

that is actually true. 
Schema ("https://" - this is schema, not protocol) is missing. It should fail like that!
Maybe we could catch this exception, and add extra, more detailed comment for users to explain that URL need schema, i.e. should start with https:// (or at least http://).
