### ISSUE TITLE
readthedocs build failed due to problematic doc/requirements.txt

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/oda_api#75]

**Comment by volodymyrss** [comment]
the problem is caused by incompatibility between setuptools-58.0.0 (released 3 days ago) and sphinx-bootstrap-theme (which is no more maintained)

**Comment by ferrigno** [comment]
I guess you solved it

**Comment by volodymyrss** [comment]
yes but please review the relevant PR, see if all looks ok. At least one notebook is not ok. This can be addressed in a separate PR of course.
readthedoc builds for each PR, so you can preview.
