### ISSUE TITLE
error in oda_api v 1.1.21

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/oda_api#84]
The API code received in the email gives a type error
TypeError: list indices must be integers or slices, not str

see below the call. **Note that I deleted my token, so please insert yours to reproduce it.**

```
from oda_api.api import DispatcherAPI

disp = DispatcherAPI(url="https://www.astro.unige.ch/mmoda//dispatch-data", instrument="mock")

par_dict = {
"osa_version": "OSA11.0-dev210827.0528-37487",
"E1_keV": "25.0",
"E2_keV": "80.0",
"integral_data_rights": "all-private",
"scw_list": [
"101900100010.001",
"101900130010.001",
"101900160010.001",
"101900190010.001",
"101900340010.001",
"101900370010.001",
"101900400010.001",
"101900540010.001",
"101900550010.001",
"101900560010.001",
"101900570010.001",
"101900580010.001",
"101900590010.001",
"101900600010.001",
"101900610010.001",
"101900620010.001",
"101900630010.001",
"101900640010.001",
"101900650010.001",
"101900660010.001",
"101900670010.001",
"101900680010.001",
"101900690010.001",
"101900700010.001",
"101900710010.001",
"101900720010.001",
"101900730010.001",
"101900740010.001",
"101900750010.001",
"101900760010.001",
"101900770010.001",
"101900790010.001",
"101900810010.001",
"101900830010.001",
"101900840010.001",
"101900860010.001",
"101900870010.001",
"101900880010.001",
"101900890010.001",
"101900900010.001",
"101900910010.001",
"101900920010.001",
"101900930010.001",
"101900940010.001",
"101900950010.001",
"101900960010.001",
"101900970010.001",
"101900980010.001",
"101901000010.001",
"101901010010.001",
"101901020010.001",
"101901030010.001",
"101901040010.001",
"101901050010.001",
"101901060010.001",
"101901070010.001",
"101901080010.001",
"101901090010.001",
"101901100010.001",
],
"selected_catalog": (
'{"cat_frame": "fk5", "cat_coord_units": "deg", "cat_column_list": [[0, 3], ["1A 0535+262",'
' "Crab"], [779.8522338867188, 1602.0269775390625], [84.72511291503906, 83.63396453857422],'
" [26.31719970703125, 22.01705551147461], [-32768, -32768], [2, 2], [0, 0],"
' [0.0002800000074785203, 0.0002800000074785203]], "cat_column_names": ["meta_ID",'
' "src_names", "significance", "ra", "dec", "NEW_SOURCE", "ISGRI_FLAG", "FLAG", "ERR_RAD"],'
' "cat_column_descr": [["meta_ID", "<i8"], ["src_names", "<U18"], ["significance", "<f8"],'
' ["ra", "<f8"], ["dec", "<f8"], ["NEW_SOURCE", "<i8"], ["ISGRI_FLAG", "<i8"], ["FLAG",'
' "<i8"], ["ERR_RAD", "|O"]], "cat_lat_name": "dec", "cat_lon_name": "ra"}'
),

"instrument": "isgri",
"product": "isgri_spectrum",
"product_type": "Real",
"off_line": "False",
"dry_run": "False",
"api": "True",
"oda_api_version": "1.1.21",
}

data_collection = disp.get_product(**par_dict)

- waiting for remote response (since 2021-09-14 10:49:57), please wait for https://www.astro.unige.ch/mmoda//dispatch-data/run_analysis
session: Y0CQ65ZT4WN6ISIG job: 7d28d401ce2f3a0d

... query status prepared => done
... assigned job id: 7d28d401ce2f3a0d
query COMPLETED SUCCESSFULLY (state done)
query complete: terminating

TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_88151/1088209492.py in <module>
     91 }
     92 
---> 93 data_collection = disp.get_product(**par_dict)

~/.venv/myVE/lib/python3.8/site-packages/oda_api/api.py in get_product(self, product, instrument, verbose, dry_run, product_type, **kwargs)
    914         else:
    915             self._decode_res_json(
--> 916                 res.json()['products']['instrument_parameters'])
    917             d = None
    918 

TypeError: list indices must be integers or slices, not str
```

**Comment by ferrigno** [comment]
Not that the original call produced a results, so it is a particular combination of parameters that causes this issue.
If I remove
"off_line": "False",
"dry_run": "False",
"api": "True",
"oda_api_version": "1.1.21",
"E1_keV": "25.0",
"E2_keV": "80.0",

the query goes through.

**Comment by volodymyrss** [comment]
it's because `dry_run` is set as string `"False"` instead of boolean. Where did the query start originally? Did it have `dry_run=False`?

**Comment by ferrigno** [comment]
The query started from a calibration workflow  (1A 0535+262) without any mention to dry_run. I copied the code from the email.

**Comment by burnout87** [comment]
A quick fix should be easy to implement though.

**Comment by volodymyrss** [comment]
> A quick fix should be easy to implement though.

It's actually rather convoluted, although still not too difficult to address.

Because of this confusion between `"False"` and `False`, dry_run was always set in the api code from email.
But because of other unexpected treatment in the API, it was not actually doing dry run.
Example with `dry_run` in `TestAPI.ipynb` is misleading or not exhaustive, since we would expect it to behave in the same way with `dry_run=False`. `dry_run=True` fails with the same error with correct parameters.

So there are two actions:

* dry_run=False is set by oda_api, and will be formatted incorrectly as a string. This is to be addressed.
* In addition, we could reinstate working `dry_run` (not sure when it actually worked), but it's not too useful. We could also eliminate or hide it.

**Comment by burnout87** [comment]
> 
>     * dry_run=False is set by oda_api, and will be formatted incorrectly as a string. This is to be addressed.
> 
I was precisely considering this option, if we decide to keep supporting it for the moment. 

Another option is also to consider the parameter value as a string.

**Comment by volodymyrss** [comment]
> > ```
> > * dry_run=False is set by oda_api, and will be formatted incorrectly as a string. This is to be addressed.
> > ```
> 
> I was precisely considering this option, if we decide to keep supporting it for the moment.

yeah but it's circumstantial since emailed API code always set it to `"False"` which is `True` in bool, so it was still working.
We should fix it for clarity though.

> Another option is also to consider the parameter value as a string.

normally, let's just sent bool as bool.
