### ISSUE TITLE
try to set default parameters

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/oda_api#86]
just not to loose track of the discussion we had.

`oda_api` already learns about the parameter list for the given instrument/product, and uses then to warn about unexpected parameters.

what we could do to address https://github.com/oda-hub/dispatcher-app/pull/233 is to also use this list of parameters, to add into the query all of the default parameters. This could be very easy.

List of the parameters with default values is already available.

**Comment by burnout87** [comment]
This is partially addressed with #88 and #87

**Comment by volodymyrss** [comment]
not completely addressed?

**Comment by burnout87** [comment]
Sorry, it was supposed to be a question. Now it is addresses completely. Right?

**Comment by volodymyrss** [comment]
Yes, that's another approach but very similar approach.
